# Generated by Django 5.1.3 on 2024-11-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_alter_user_bio_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='interested_users', to='userauth.interest'),
        ),
    ]
