# Generated by Django 5.1.3 on 2024-12-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_remove_user_interests_user_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, null=True, verbose_name='Interests'),
        ),
    ]
