# Generated by Django 5.1.3 on 2025-05-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0014_user_faculty_user_university_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
