# Generated by Django 5.1.3 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0016_alter_user_bio_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(
                blank=True,
                related_name='interested_users',
                to='userauth.interest',
            ),
        ),
    ]
