# Generated by Django 5.1.3 on 2026-07-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_like_created_at'),
        ('posts', '0004_social_media_threading'),
    ]

    operations = [
    ]
