# Generated by Django 5.1.3 on 2026-07-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='community',
            new_name='communities_visibil_10961c_idx',
            old_name='communities_visibil_3d61cc_idx',
        ),
        migrations.RenameIndex(
            model_name='community',
            new_name='communities_categor_8090ae_idx',
            old_name='communities_categor_a3dbad_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymembership',
            new_name='communities_communi_bed585_idx',
            old_name='communities_communi_b1130a_idx',
        ),
        migrations.RenameIndex(
            model_name='communitymembership',
            new_name='communities_user_id_1e5b66_idx',
            old_name='communities_user_id_d86418_idx',
        ),
        migrations.RenameIndex(
            model_name='communitypost',
            new_name='communities_communi_ef379f_idx',
            old_name='communities_communi_f7ca2a_idx',
        ),
        migrations.RenameIndex(
            model_name='communityresource',
            new_name='communities_communi_abf189_idx',
            old_name='communities_communi_b7c8dc_idx',
        ),
    ]
