# Generated by Django 5.1.3 on 2026-07-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_684eac_idx',
            old_name='notificatio_recipie_90987d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_verb_ecd1b6_idx',
            old_name='notificatio_verb_91fa2b_idx',
        ),
    ]
