# Generated by Django 5.1.3 on 2026-07-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
        ('notifications', '0002_rename_notificatio_recipie_90987d_idx_notificatio_recipie_684eac_idx_and_more'),
    ]

    operations = [
    ]
