# Generated by Django 5.1.3 on 2026-07-11 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_direct_group_calls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
    ]
