# Generated by Django 5.1.3 on 2024-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='Image',
            field=models.ImageField(blank=True, height_field=300, null=True, upload_to='adverts/', width_field=300),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(upload_to='adverts/'),
        ),
    ]
