# Generated by Django 5.1.3 on 2026-07-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_production_marketplace'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='advertisement',
            new_name='marketplace_status_d17ddf_idx',
            old_name='marketplace_status_47559d_idx',
        ),
        migrations.RenameIndex(
            model_name='advertisement',
            new_name='marketplace_user_id_db42ac_idx',
            old_name='marketplace_user_id_946ca8_idx',
        ),
        migrations.RenameIndex(
            model_name='advertisement',
            new_name='marketplace_price_243716_idx',
            old_name='marketplace_price_c7360b_idx',
        ),
    ]
